stages:
  - gitops

# Bootstrap Flux
# this needs to be done only once and ensure the $CI_COMMIT_AUTHOR is not your token
bootstrap-flux:
  stage: gitops
  only:
    - triggers
  image:
    name: registry.gitlab.com/kameshsampath/kube-dev-tools
    entrypoint: [""]
  variables:
    GITLAB_TOKEN: $FLUX_PROJECT_ACCESS_TOKEN
  before_script:
    - echo "Jai Guru"
    - kubectl config get-contexts
    - kubectx $CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:gke-agent
    - kubectl get pods
  script: |
    trigger_ref=$(cat $TRIGGER_PAYLOAD | jq '.ref')
    echo "Using ref $trigger_ref from trigger"
    flux bootstrap gitlab \
    --owner=$CI_PROJECT_NAMESPACE \
    --repository=$CI_PROJECT_NAME \
    --branch=$trigger_ref \
    --path=clusters/dev \
    --token-auth \
    --personal
