# https://taskfile.dev

version: "3"

vars:
  TFVARS_FILE: .local.tfvars

dotenv:
  - .env

includes:
  infra: infra/Taskfile.yaml
  dir: infra

tasks:
  clean:
    desc: Clean all terraform artifacts/assets
    silent: true
    cmds:
      - task infra:clean

  format:
    desc: Format terraform files
    silent: true
    cmds:
      - terraform fmt --recursive {{.ROOT_DIR}}

  init:
    desc: Init terraform working directory
    silent: true
    cmds:
      - mkdir -p {{.ROOT_DIR}}/.kube
      - task infra:init

  validate:
    silent: true
    desc: Validate the terraform resources
    cmds:
      - task infra:validate

  create_cluster:
    silent: true
    aliases:
      - create
    desc: Create the GKE cluster
    cmds:
      - task infra:create_cluster

  destroy:
    silent: true
    desc: Destroys terraform resources
    cmds:
      - task infra:destroy


  readme:
    desc: Build readme
    silent: true
    cmds:
      - terraform-docs infra > {{.ROOT_DIR}}/README.md

  get_kubeconfig:
    silent: true
    desc: Get Kubeconfig of the cluster
    generates:
      - "{{.ROOT_DIR}}/.kube/config"
    aliases:
      - kubeconfig
    cmds:
      - mkdir -p {{.ROOT_DIR}}/.kube
      - gcloud container clusters get-credentials {{.CLUSTER_NAME}} --zone={{.CLUSTER_ZONE}}
    vars:
      CLUSTER_NAME:
        sh: terraform output -raw kubernetes-cluster-name
      CLUSTER_ZONE:
        sh: terraform output -raw zone

  flux_bootstrap:
    silent: true
    desc: Bootstrap flux
    cmds:
      - |
        flux bootstrap gitlab \
        --owner=$CI_PROJECT_NAMESPACE \
        --repository=$CI_PROJECT_NAME \
        --branch=main \
        --path=clusters/dev \
        --token-auth \
        --personal

  call_service:
    desc: Calls the lingua-greeter service
    silent: true
    cmds:
      - curl -s "http://{{.SERVICE_IP}}/{{.LANG}}"
    vars:
      SERVICE_IP:
        sh: kubectl get svc -n demo-apps lingua-greeter -ojsonpath="{.status.loadBalancer.ingress[*].ip}"

  patch_flux_sa:
    desc: patch flux source controller to use workload identity
    silent: true
    cmds:
      - sed '10,$s/^# //' {{.ROOT_DIR}}/clusters/dev/flux-system/kustomization.yaml | envsubst > {{.ROOT_DIR}}/clusters/dev/flux-system/kustomization.yaml.tmp
      - mv {{.ROOT_DIR}}/clusters/dev/flux-system/kustomization.yaml.tmp {{.ROOT_DIR}}/clusters/dev/flux-system/kustomization.yaml
