apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml

# Uncomment Line 10-20 to allow flux source-controller to use Workload Identity 
# and pull OCI Manifest Repo. 
# More info check https://fluxcd.io/flux/components/source/ocirepositories/#gcp
# patches:
#   - patch: |
#       apiVersion: v1
#       kind: ServiceAccount
#       metadata:
#         name: source-controller
#         annotations:
#           iam.gke.io/gcp-service-account: gar-reader@$GCP_PROJECT.iam.gserviceaccount.com    
#     target:
#       kind: ServiceAccount
#       name: source-controller
